### ISSUE TITLE
Documentation for building the demo in ubuntu?

### ISSUE THREAD

**Issue by im-sj** [versatica/mediasoup-broadcaster-demo#11]
I am trying to build this demo on my linux machine and getting compilation errors:

=========== libmediasoupclient Build Configuration ===========

-- MEDIASOUPCLIENT_BUILD_TESTS : OFF
-- MEDIASOUPCLIENT_LOG_TRACE   : OFF
-- MEDIASOUPCLIENT_LOG_DEV     : OFF
-- LIBWEBRTC_INCLUDE_PATH      : /home/sumitj/webrtc-checkout-m84/src
-- LIBWEBRTC_BINARY_PATH       : /home/sumitj/webrtc-checkout-m84/src/out/m84/obj

**CMake Error at CMakeLists.txt:58 (target_include_directories):
  Cannot specify include directories for target "broadcaster" which is not
  built by this project.

CMake Error at CMakeLists.txt:65 (target_link_libraries):
  Cannot specify link libraries for target "broadcaster" which is not built
  by this project.**

My build specs:
Ubuntu 18.04
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
cmake version 3.10.2

I looked into the forums (https://github.com/versatica/mediasoup-broadcaster-demo/issues/2) and upgraded the cmake version to 14.4 and got different errors now:
make: Entering directory '/home/sumitj/bodyline/third_party/mediasoup-broadcaster-demo/build'
make[1]: Entering directory '/home/sumitj/bodyline/third_party/mediasoup-broadcaster-demo/build'
make[2]: Entering directory '/home/sumitj/bodyline/third_party/mediasoup-broadcaster-demo/build'
make[2]: Leaving directory '/home/sumitj/bodyline/third_party/mediasoup-broadcaster-demo/build'
make[2]: Entering directory '/home/sumitj/bodyline/third_party/mediasoup-broadcaster-demo/build'
[  0%] Building CXX object libwebrtc/CMakeFiles/webrtc_broadcaster.dir/test/testsupport/ios_file_utils.mm.o
c++: error trying to exec 'cc1objplus': execvp: No such file or directory
libwebrtc/CMakeFiles/webrtc_broadcaster.dir/build.make:205: recipe for target 'libwebrtc/CMakeFiles/webrtc_broadcaster.dir/test/testsupport/ios_file_utils.mm.o' failed
make[2]: *** [libwebrtc/CMakeFiles/webrtc_broadcaster.dir/test/testsupport/ios_file_utils.mm.o] Error 1
make[2]: Leaving directory '/home/sumitj/bodyline/third_party/mediasoup-broadcaster-demo/build'
CMakeFiles/Makefile2:1657: recipe for target 'libwebrtc/CMakeFiles/webrtc_broadcaster.dir/all' failed
make[1]: *** [libwebrtc/CMakeFiles/webrtc_broadcaster.dir/all] Error 2
make[1]: Leaving directory '/home/sumitj/bodyline/third_party/mediasoup-broadcaster-demo/build'
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
make: Leaving directory '/home/sumitj/bodyline/third_party/mediasoup-broadcaster-demo/build'

As an FYI, I followed the documentation for libmediasoupclient for installing webrtc and exactly did what is mentioned here:
https://mediasoup.org/documentation/v3/libmediasoupclient/installation/.  Is there another branch head I should be trying with instead of m84?

Possibly related issue I filed for libmediasoupclient: https://github.com/versatica/libmediasoupclient/issues/89

**Comment by jmillan** [comment]
Please try with a higher CMake version, like 14. We are will enhance the build process to support older CMake versions.

https://github.com/versatica/mediasoup-broadcaster-demo/issues/2

Closing the issue. If you have further questions use the [forum](https://mediasoup.discourse.group/c/mediasoup-libraries)

**Comment by im-sj** [comment]
Reopening: As I mentioned in the description above, the error log is using cmake 14.4
