### ISSUE TITLE
Project doesn't work when pointing to https://v3demo.mediasoup.org

### ISSUE THREAD

**Issue by EyalSi** [versatica/mediasoup-broadcaster-demo#15]
Just compiled the project on aws server, and trying to run it against https://v3demo.mediasoup.org, by using the command line:
SERVER_URL=https://v3demo.mediasoup.org ROOM_ID=8ktvbiip build/broadcaster

It's not working as the url:
https://v3demo.mediasoup.org/rooms/8ktvbiip 
returns 404.
Should it work with V3? can it only work in local installations?

10x,
EyalS

**Comment by alexfreed58** [comment]
I can't make it work with either SERVER_URL=https://v3demo.mediasoup.org  or the v3demo I run locally. No problem connecting to it from Chrome on another computer on the same subnet. 
Looks like there is an attempt to get /rooms/xxxx and it always fail. Even trying to get it from a browser ends in "cant GET ..."

Did the interface change? When I connect to the demo room from Chrome, there is no call to /rooms/xxx. So how am I supposed to get the routerRtpCapabilities?

**Comment by jmillan** [comment]
Please use the [mediasoup forum](https://mediasoup.discourse.group/c/mediasoup-demo/8) for this kind of questions.
