### ISSUE TITLE
compile error on Mac - can't use built in openssl lib

### ISSUE THREAD

**Issue by spiderman22** [versatica/mediasoup-broadcaster-demo#16]
Im trying to compile the lib on MacOS Catalina.

In the last step: make -C build
The process fails with the message:

`
[ 65%] Linking C shared library ../../../../lib/libcurl.dylib
ld: cannot link directly with dylib/framework, your binary is not an allowed client of /usr/lib/libcrypto.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libcurl.dylib] Error 1
make[1]: *** [cpr/opt/curl/lib/CMakeFiles/libcurl.dir/all] Error 2
make: *** [all] Error 2
`
Note: I have set the PATH_TO_OPENSSL_HEADERS in the command to /usr/local/opt/openssl/include as instructed in the README

Any solutions to this?

**Comment by ibc** [comment]
Please use the mediasoup forum.
