### ISSUE TITLE
App crashed in when connect with server using IOS

### ISSUE THREAD

**Issue by sivakumaraketi** [versatica/mediasoup-broadcaster-demo#17]
RoomListener::onNewConsumer kind=video
[WARN] PeerConnection::OnFailure() | webtc::SetSessionDescriptionObserver failure [INVALID_PARAMETER:Failed to set remote offer sdp: Duplicate a=mid value '1'.]
[ERROR] transport_wrapper::+[TransportWrapper nativeConsume:listener:id:producerId:kind:rtpParameters:appData:]() | Failed to set remote offer sdp: Duplicate a=mid value '1'.

**Comment by jmillan** [comment]
- Are you using the libemdiasoupclient C++ implementation?
- Are you using the last libemdiasoupclient C++ implementation?

**Comment by sivakumaraketi** [comment]
Yes using C++ implementation

**Comment by jmillan** [comment]
* Are you using the last libemdiasoupclient C++ implementation?

☝️

**Comment by jmillan** [comment]
> set remote offer sdp: Duplicate a=mid value '1'.

Can you spot why is this happening looking at the logs and the SDPs that are being set? Otherwise paste here the logs within the SDP exchanges.

**Comment by jmillan** [comment]
closed due to inactivity
