### ISSUE TITLE
Missing include in Logger.cpp

### ISSUE THREAD

**Issue by alexfreed58** [versatica/mediasoup-broadcaster-demo#20]
Couldn't build out of the box because uint8_t was undefined and used in Ligger.hpp
#include <cstdint> 
takes care of the issue. I guess opened and closed, but may help somebody.

**Comment by jmillan** [comment]
Please be more explicit and indicate exactly the issue.

**Comment by ibc** [comment]
Hi @jmillan, this bug was also reported (wrongly as well) by other users. The thing is that in Logger.hpp we are not including `<cstdint>` so it fails in Windows due to lack of `uint8_t`.

**Comment by jmillan** [comment]
>  this bug was also reported (wrongly as well) by other users. 

That's incorrect. Indeed it was fixed in libmediasoupclient by the user who reported it, but as I see the dep was not updated in broadcaster demo, on it.

**Comment by jmillan** [comment]
libmediasoup dependency (with the fix in Logger.hpp) has been updated.
