### ISSUE TITLE
Overlay stream trouble

### ISSUE THREAD

**Issue by Able1991** [versatica/mediasoup-broadcaster-demo#22]
Hi, I experimenting with this demo, sending generally works (a bit confusing how to control the bitrate, but I think I'll find the answer in the mediasoup documentation).

The problem occurred while trying to overlay a stream from mediasoup to another stream (udp, rtmp, etc.).

I understand that this is not a problem with this repository, but perhaps a fresh look and experience with mediaasoup will help localize the problem.

According to ffmpeg logs, it starts working, processes for a while and stops (line 957 of the log file)

I suspect there is something wrong with the stream from mediaasoup

Logs: https://gist.github.com/Able1991/b59bd18cc44a1b9b08c3df4cd5dbe08a

Start command:
`ffmpeg -strict experimental -loglevel debug -protocol_whitelist pipe,udp,rtp -fflags +genpts -flags low_delay -f sdp -analyzeduration 2147483647 -probesize 2147483647 -i pipe:0 -fflags +nobuffer -analyzeduration 10000000 -probesize 10000000 -i rtmp://eu-02.re.stream.mvs.wtf:1936/monitor/pV2ErmcZIscDsaoU8AS4KuYYYZG_-wPDiH_sDeu6U58 -filter_complex [0:a]asetpts=PTS-STARTPTS[a0];[1:a]asetpts=PTS-STARTPTS[a1];[0:v]setpts=PTS-STARTPTS,scale=iw/3:ih/3[pip];[1:v]setpts=PTS-STARTPTS[v1];[v1][pip]overlay=0:0:shortest=0[vo];[a0][a1]amix=inputs=2[ao] -map [vo] -map [ao] -c:a aac -c:v h264 -s 640x480 -r 30 -x264opts keyint=60:keyint_min=60:no-scenecut -preset superfast -profile:v high -level:v 4.1 -tune zerolatency -f flv -max_muxing_queue_size 4096 rtmp://publish.stream.mvs.wtf/push/LFcDPV65OWznyhAjcSvOqhcxN9BRFBijP7jFakjweR0
`

sdp:
> v=0
> o=- 0 0 IN IP4 127.0.0.1
> s=FFmpeg
> c=IN IP4 127.0.0.1
> t=0 0
> m=video 26692 RTP/AVP 101
> a=rtpmap:101 VP8/90000
> a=sendonly
> m=audio 26267 RTP/AVP 100
> a=rtpmap:100 opus/48000/2
> a=sendonly

**Comment by ibc** [comment]
Please don't open a bug report for this. Use the mediasoup public forum for questions or usage problems. BTW your question is about ffmpeg rather than mediasoup ecosystem.
