### ISSUE TITLE
Excuse me! Does the latest mediasoup supported the latest webrtc（release M79）

### ISSUE THREAD

**Issue by wuliuquan-ch** [versatica/mediasoup-broadcaster-demo#24]
Excuse me! Does the latest mediasoup supported the latest webrtc（release M79）

**Comment by ibc** [comment]
STOP. Use the mediasoup forum.

**Comment by wuliuquan-ch** [comment]
please help me


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "versatica/mediasoup-broadcaster-demo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月5日(星期二) 下午4:40
收件人:&nbsp;"versatica/mediasoup-broadcaster-demo"<mediasoup-broadcaster-demo@noreply.github.com&gt;;
抄送:&nbsp;"冰泪情缘"<751591413@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [versatica/mediasoup-broadcaster-demo] Excuse me! Does the latest mediasoup supported the latest webrtc（release M79） (#24)





 
Closed #24.

**Comment by wuliuquan-ch** [comment]
OK&nbsp; thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "versatica/mediasoup-broadcaster-demo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月5日(星期二) 下午4:40
收件人:&nbsp;"versatica/mediasoup-broadcaster-demo"<mediasoup-broadcaster-demo@noreply.github.com&gt;;
抄送:&nbsp;"冰泪情缘"<751591413@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [versatica/mediasoup-broadcaster-demo] Excuse me! Does the latest mediasoup supported the latest webrtc（release M79） (#24)





 
STOP. Use the mediasoup forum.
