### ISSUE TITLE
Issue compiling: missing rtc_base/critical_section.h

### ISSUE THREAD

**Issue by Radagan** [versatica/mediasoup-broadcaster-demo#29]
I'm trying to compile this demo under macOS using webrtc branch 4606 (m94). It appears there is a missing file. Are we still using 4606 as described in the Mediasoup docs? 

```
cmake . -Bbuild \
-DLIBWEBRTC_INCLUDE_PATH:PATH="~/Development/GitHub/webrtc-checkout/src" \
-DLIBWEBRTC_BINARY_PATH:PATH="~/Development/GitHub/webrtc-checkout/src/out/mac_x64" \
-DOPENSSL_INCLUDE_DIR:PATH="/usr/local/opt/openssl/include" \
-DOPENSSL_ROOT_DIR:PATH="/usr/local/opt/openssl/lib" \
-DCMAKE_USE_OPENSSL=ON
```

**Comment by jmillan** [comment]
Hi, 

`mediasoup-broadcaster-demo` needs to be adapted to M94 code. Will try to do it in the next days.

**Comment by Radagan** [comment]
@jmillan Thank you! No problem.

**Comment by Radagan** [comment]
@jmillan, Btw, I was looking at this example in the hopes of understanding how to use part of mediasoup as a traditional peer connection solution that could be switched to using mediasoup SFUs. Do you know if this is possible? 

The assumption being that it would greatly reduce costs to use peer-to-peer for connections with just two or three users, then switch to SFUs where they are needed.

**Comment by ibc** [comment]
Please use the forum for questions and avoid direct mentions to authors. Thanks.

**Comment by Radagan** [comment]
@ibc Sorry, I was just trying to see it this example's purpose was as I understood it--since it doesn't build at this point.

**Comment by jmillan** [comment]
Demo updated.
