### ISSUE TITLE
media_stream_interface

### ISSUE THREAD

**Issue by dullor** [versatica/mediasoup-broadcaster-demo#3]
When I do make -C build, it shows:
In file included from /home/shengqi/mediasoup-broadcaster-demo/deps/libmediasoupclient/src/Consumer.cpp:4:0:
/home/shengqi/mediasoup-broadcaster-demo/deps/libmediasoupclient/include/Consumer.hpp:6:10: fatal error: api/media_stream_interface.h: no such a file or dic

I  cannot find any media_stream_interface.h in my files, what does it mean? Should I customize it or pre-install other things? Thanks!

**Comment by ibc** [comment]
You are not correctly referencing the libwebrtc paths. Read the [Installation](https://mediasoup.org/documentation/v3/libmediasoupclient/installation/) documentation of libmediasoupclient.

Also, please use the new forum for usage problems and questions:

https://mediasoup.discourse.group/
