### ISSUE TITLE
 OnConnect(mediasoupclient::Transport* transport, const nlohmann::json& dtlsParameters)  why no callback ?

### ISSUE THREAD

**Issue by jackwxs** [versatica/mediasoup-broadcaster-demo#30]
![image](https://user-images.githubusercontent.com/28855943/170830586-acba301d-149a-4936-9c9f-37d977f37785.png)
![image](https://user-images.githubusercontent.com/28855943/170830640-a8d5a7bc-d1bc-4d27-9c94-8c3710d00dee.png)

![image](https://user-images.githubusercontent.com/28855943/170830608-93586be6-9888-45d5-8700-d5be01da46f3.png)

**Comment by jmillan** [comment]
The code shown does not belong to the repository, nor does the issue contain any explanation of any kind.

Closing.
