### ISSUE TITLE
mac linker error

### ISSUE THREAD

**Issue by hanson1977** [versatica/mediasoup-broadcaster-demo#5]
I build demo on mac os
step 1:
cmake . -Bbuild                                            \
-DLIBWEBRTC_INCLUDE_PATH:PATH=/Users/hanson/webrtc-checkout/src \
-DLIBWEBRTC_BINARY_PATH:PATH=/Users/hanson/webrtc-checkout/out/Release/obj \
-DOPENSSL_INCLUDE_DIR:PATH=/opt//local/include  \
-DCMAKE_USE_OPENSSL=ON
step2:
cd build
make

error:
Undefined symbols for architecture x86_64:
  "typeinfo for webrtc::VideoTrackSource", referenced from:
      typeinfo for CapturerTrackSource in peerConnectionUtils.cpp.o
  "typeinfo for webrtc::SetSessionDescriptionObserver", referenced from:
      typeinfo for mediasoupclient::PeerConnection::SetSessionDescriptionObserver in Broadcaster.cpp.o
      typeinfo for mediasoupclient::PeerConnection::SetSessionDescriptionObserver in main.cpp.o
      typeinfo for mediasoupclient::PeerConnection::SetSessionDescriptionObserver in libmediasoupclient.a(mediasoupclient.cpp.o)
      typeinfo for mediasoupclient::PeerConnection::SetSessionDescriptionObserver in libmediasoupclient.a(Transport.cpp.o)
      typeinfo for mediasoupclient::PeerConnection::SetSessionDescriptionObserver in libmediasoupclient.a(PeerConnection.cpp.o)
      typeinfo for mediasoupclient::PeerConnection::SetSessionDescriptionObserver in libmediasoupclient.a(Device.cpp.o)
      typeinfo for mediasoupclient::PeerConnection::SetSessionDescriptionObserver in libmediasoupclient.a(Handler.cpp.o)
      ...
  "typeinfo for webrtc::CreateSessionDescriptionObserver", referenced from:
      typeinfo for mediasoupclient::PeerConnection::CreateSessionDescriptionObserver in Broadcaster.cpp.o
      typeinfo for mediasoupclient::PeerConnection::CreateSessionDescriptionObserver in main.cpp.o
      typeinfo for mediasoupclient::PeerConnection::CreateSessionDescriptionObserver in libmediasoupclient.a(mediasoupclient.cpp.o)
      typeinfo for mediasoupclient::PeerConnection::CreateSessionDescriptionObserver in libmediasoupclient.a(Transport.cpp.o)
      typeinfo for mediasoupclient::PeerConnection::CreateSessionDescriptionObserver in libmediasoupclient.a(PeerConnection.cpp.o)
      typeinfo for mediasoupclient::PeerConnection::CreateSessionDescriptionObserver in libmediasoupclient.a(Device.cpp.o)
      typeinfo for mediasoupclient::PeerConnection::CreateSessionDescriptionObserver in libmediasoupclient.a(Handler.cpp.o)
      ...
ld: symbol(s) not found for architecture x86_64

any idea? thanks

**Comment by ibc** [comment]
It looks like you did not compile libwebrtc but just reference those dirs.
